## This file is automatically generated
## Standard maketest.g for the G-Modules project

LoadPackage( "G-Modules" );
LoadPackage( "Modules" );
Read( "ListOfDocFiles.g" );
example_tree := ExtractExamples( DirectoriesPackageLibrary( "G-Modules", "doc" )[1]![1], "G-Modules.xml", list, 500 );
RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );
GAPDocManualLab( "G-Modules" );
QUIT;
